# Generated by Django 5.0.3 on 2024-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('fips', models.IntegerField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FaceMasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countyfp', models.IntegerField()),
                ('never', models.FloatField()),
                ('rarely', models.FloatField()),
                ('sometimes', models.FloatField()),
                ('frequently', models.FloatField()),
                ('always', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('fips', models.IntegerField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='facemasks',
            constraint=models.UniqueConstraint(fields=('countyfp',), name='unique_countyfp'),
        ),
    ]
